version: '3'
services:
  
  app:
    image: <service-container-url>:local
    build:
      context: ../..
      dockerfile: build/Dockerfile
    env_file:
      - ../../configs/.env
    depends_on:
      - db
    ports:
      - "4445:4445"
  
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../../configs/.env
  
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      #- "6831:6831/udp"
      #- "6832:6832/udp"
      #- "5778:5778"
      - "16686:16686" #webui
      #- "4317:4317"
      #- "4318:4318"
      #- "14250:14250"
      #- "14268:14268"
      #- "14269:14269"
      #- "9411:9411"

volumes:
  postgres-data:


